print('-' * 35)
print('Tugas 1 SISOP Kelas-A')
print('-' * 35)
print('Nama: Cesaria Deby Nurhalizah')
print('NPM: 21083010120')
print('-' * 35)
print('notes: ')
print('-' * 35)
print('Halo Dunia!')
print('Ini adalah script Bash pertamaku di Linux')
